[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://bsf-farm-backend.onrender.com/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"