services:
  - type: web
    name: bsf-farm-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 3 -b 0.0.0.0:8000 app:app
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: API_BASE_URL
        value: https://bsf-farm-backend.onrender.com
      - key: API_DEBUG
        value: "false"
    autoDeploy: true
    healthCheckPath: /
    region: frankfurt